use_frameworks!

platform :ios, '10.0'

target 'ContextMenuSwift_Example' do
  pod 'ContextMenuSwift', :path => '../'

  target 'ContextMenuSwift_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
